# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "上传测试版本到蒲公英"
  lane :beta_pgy do
    # add actions here: https://docs.fastlane.tools/actions

    scheme_name = "mix"

    increment_build_number

    version = get_info_plist_value(path: "./#{scheme_name}/Info.plist", key: "CFBundleShortVersionString")
    build = get_info_plist_value(path: "./#{scheme_name}/Info.plist", key: "CFBundleVersion")

    output_name = "#{scheme_name}_#{version}_#{build}_#{Time.now.strftime('%Y%m%d%H%M%S')}.ipa"

    gym(
        scheme: "#{scheme_name}",
        export_method: "ad-hoc",
        export_xcargs: "-allowProvisioningUpdates",
        output_directory: "/Users/json/Desktop/ipa测试包",
        output_name: "#{output_name}",
        silent: true,  # 隐藏没有必要的信息
        clean: true  # 在构建前先clean
    )
    pgyer(
        api_key: "d66b4846e3ca30ee79e7a7600895d0c9",
        user_key: "46cb0a82789b2e608d092eb1343a95de",
        # update_description: get_update_description(),
        # password: "123456",
        # install_type: "2"
    )


  end
end
